/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

import com.ideiah.controller.ChaveController;
import com.ideiah.model.entity.Chave;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruna
 */
public class CadastroChaveLote extends javax.swing.JPanel {

    /**
     * Creates new form CadastroChaveLote
     */
    
    public CadastroChaveLote() {
        initComponents();
    }

    
    public boolean verificaFormatoChave(String texto){
       
            try {  
                Double value = Double.parseDouble(texto);  
                return true;
            } catch (NumberFormatException ex) {  
                return false;
            }  
    }
    
    public boolean verificaSelecao(){
       
            if(this.jComboBox_listaTamChaveLote.getSelectedItem() != "-")
                return true;
            else
                return false;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_cadNumeroInicial = new javax.swing.JLabel();
        jTF_cadNumChaveInicial = new javax.swing.JTextField();
        jButton_cadastrarLote = new javax.swing.JButton();
        jLabel_cadTamanhoChaveLote = new javax.swing.JLabel();
        jComboBox_listaTamChaveLote = new javax.swing.JComboBox();
        jLabel_tituloCadastro = new javax.swing.JLabel();
        jTF_cadNumChaveFinal = new javax.swing.JTextField();
        jLabel_cadNumeroFinal = new javax.swing.JLabel();
        jLabel_alertaInicial = new javax.swing.JLabel();
        jLabel_alertaFinal = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(609, 527));

        jLabel_cadNumeroInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadNumeroInicial.setText("Número da chave inicial:");

        jTF_cadNumChaveInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_cadastrarLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_cadastrarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_cadastrarLote.setText("Cadastrar");
        jButton_cadastrarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarLoteActionPerformed(evt);
            }
        });

        jLabel_cadTamanhoChaveLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadTamanhoChaveLote.setText("Tamanho do armário:");

        jComboBox_listaTamChaveLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaTamChaveLote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Menor", "Maior" }));
        jComboBox_listaTamChaveLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaTamChaveLoteActionPerformed(evt);
            }
        });

        jLabel_tituloCadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_tituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tituloCadastro.setText("Cadastro de novo número de chave em lote");

        jTF_cadNumChaveFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_cadNumeroFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadNumeroFinal.setText("Número da chave final:");

        jLabel_alertaInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alertaInicial.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alertaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alertaInicial.setText("Número de chave inválido");

        jLabel_alertaFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alertaFinal.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alertaFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alertaFinal.setText("Número de chave inválido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cadTamanhoChaveLote)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_cadNumeroFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(391, 391, 391))
                            .addComponent(jLabel_cadNumeroInicial))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cadastrarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTF_cadNumChaveFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_alertaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_listaTamChaveLote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTF_cadNumChaveInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_alertaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_tituloCadastro)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_cadNumChaveInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cadNumeroInicial)
                    .addComponent(jLabel_alertaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_cadNumChaveFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cadNumeroFinal)
                    .addComponent(jLabel_alertaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cadTamanhoChaveLote)
                    .addComponent(jComboBox_listaTamChaveLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jButton_cadastrarLote)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_listaTamChaveLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaTamChaveLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaTamChaveLoteActionPerformed

    private void jButton_cadastrarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarLoteActionPerformed
        // TODO add your handling code here:
        List<Chave> chaves = new ArrayList<Chave>();
        Integer start = Integer.decode(this.jTF_cadNumChaveInicial.getText());
        Integer end = Integer.decode(this.jTF_cadNumChaveFinal.getText());
        
        for (int i = start; i <= end; i++) {
            Chave chave = new Chave();
            if(verificaFormatoChave(this.jTF_cadNumChaveInicial.getText()) && verificaFormatoChave(this.jTF_cadNumChaveFinal.getText())){
                
                if(verificaSelecao()){
                    chave.setNumero(i);
                    String tamanho = (String)this.jComboBox_listaTamChaveLote.getItemAt(
                            this.jComboBox_listaTamChaveLote.getSelectedIndex());
                    tamanho = tamanho.toLowerCase();
                    chave.setTipo(tamanho);
                    chave.setDisponivel(true);
                    chaves.add(chave);
                }else{
                    JOptionPane.showMessageDialog(null, "Selecione um tamanho!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Digite somente números!");
                this.jTF_cadNumChaveInicial.grabFocus();
            }
        }
        new ChaveController().salvarLote(chaves);
    }//GEN-LAST:event_jButton_cadastrarLoteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrarLote;
    private javax.swing.JComboBox jComboBox_listaTamChaveLote;
    private javax.swing.JLabel jLabel_alertaFinal;
    private javax.swing.JLabel jLabel_alertaInicial;
    private javax.swing.JLabel jLabel_cadNumeroFinal;
    private javax.swing.JLabel jLabel_cadNumeroInicial;
    private javax.swing.JLabel jLabel_cadTamanhoChaveLote;
    private javax.swing.JLabel jLabel_tituloCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_cadNumChaveFinal;
    private javax.swing.JTextField jTF_cadNumChaveInicial;
    // End of variables declaration//GEN-END:variables
}
