/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

/**
 *
 * @author Bruna
 */
public class CadastroChaveLote extends javax.swing.JPanel {

    /**
     * Creates new form CadastroChaveLote
     */
    public CadastroChaveLote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_cadNumeroInicial = new javax.swing.JLabel();
        jTF_cadNumChaveInicial = new javax.swing.JTextField();
        jButton_cadastrarLote = new javax.swing.JButton();
        jLabel_cadTamanhoChaveLote = new javax.swing.JLabel();
        jComboBox_listaTamChaveLote = new javax.swing.JComboBox();
        jLabel_tituloCadastro = new javax.swing.JLabel();
        jTF_cadNumChaveFinal = new javax.swing.JTextField();
        jLabel_cadNumeroFinal = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(609, 527));

        jLabel_cadNumeroInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadNumeroInicial.setText("Número da chave inicial:");

        jTF_cadNumChaveInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_cadastrarLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_cadastrarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_cadastrarLote.setText("Cadastrar");
        jButton_cadastrarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarLoteActionPerformed(evt);
            }
        });

        jLabel_cadTamanhoChaveLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadTamanhoChaveLote.setText("Número da chave:");

        jComboBox_listaTamChaveLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaTamChaveLote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Menor", "Maior" }));
        jComboBox_listaTamChaveLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaTamChaveLoteActionPerformed(evt);
            }
        });

        jLabel_tituloCadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_tituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tituloCadastro.setText("Cadastro de novo número de chave em lote");

        jTF_cadNumChaveFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_cadNumeroFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadNumeroFinal.setText("Número da chave final:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_cadTamanhoChaveLote)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_cadNumeroFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(75, 75, 75)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_cadNumChaveFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_listaTamChaveLote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(216, 216, 216))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_cadNumeroInicial)
                                .addGap(75, 75, 75)
                                .addComponent(jTF_cadNumChaveInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_cadastrarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_tituloCadastro)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_cadNumChaveInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cadNumeroInicial))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_cadNumChaveFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cadNumeroFinal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cadTamanhoChaveLote)
                    .addComponent(jComboBox_listaTamChaveLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jButton_cadastrarLote)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_listaTamChaveLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaTamChaveLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaTamChaveLoteActionPerformed

    private void jButton_cadastrarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarLoteActionPerformed
        // TODO add your handling code here:
        //this.jButton_buscar.setBack
    }//GEN-LAST:event_jButton_cadastrarLoteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrarLote;
    private javax.swing.JComboBox jComboBox_listaTamChaveLote;
    private javax.swing.JLabel jLabel_cadNumeroFinal;
    private javax.swing.JLabel jLabel_cadNumeroInicial;
    private javax.swing.JLabel jLabel_cadTamanhoChaveLote;
    private javax.swing.JLabel jLabel_tituloCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_cadNumChaveFinal;
    private javax.swing.JTextField jTF_cadNumChaveInicial;
    // End of variables declaration//GEN-END:variables
}
