/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Bruna
 */
public class EmprestimoDevolucao extends javax.swing.JFrame {

    /**
     * Creates new form EmprestimoDevolucao
     */
    public EmprestimoDevolucao() {
        initComponents();
        //this.jButton_EmprestimoDevolucao.setVisible(false);
        this.jTF_matriculaBuscar.grabFocus();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
          try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jPanel_menor1 = new javax.swing.JPanel();
        jButton_CadastrarChave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_ListaAluno = new javax.swing.JButton();
        jLabel_dataAtual = new javax.swing.JLabel();
        jLabel_dataBuscada = new javax.swing.JLabel();
        jLabel_horaBuscada = new javax.swing.JLabel();
        jLabel_horaAtual = new javax.swing.JLabel();
        jLabel_NomeUser = new javax.swing.JLabel();
        jButton_EmprestimoDevolucao = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jLabel_logoUnipampa = new javax.swing.JLabel();
        jPanel_menor = new javax.swing.JPanel();
        jLabel_matriculaBuscar = new javax.swing.JLabel();
        jTF_matriculaBuscar = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_curso = new javax.swing.JLabel();
        jLabel_nomeBuscado = new javax.swing.JLabel();
        jLabel_cursoBuscad = new javax.swing.JLabel();
        jLabel_numChave = new javax.swing.JLabel();
        jComboBox_listaNumChavesMenores = new javax.swing.JComboBox();
        jButton_realizarEmprestimo = new javax.swing.JButton();
        jComboBox_listaNumChavesMaiores = new javax.swing.JComboBox();
        jRadioButton_armarioMaior = new javax.swing.JRadioButton();
        jRadioButton_armarioMenor = new javax.swing.JRadioButton();
        jLabel_alerta = new javax.swing.JLabel();
        jSeparator_meio3 = new javax.swing.JSeparator();
        jLabel_alerta1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_matriculaBuscarD = new javax.swing.JLabel();
        jTF_matriculaBuscarD = new javax.swing.JTextField();
        jButton_buscarD = new javax.swing.JButton();
        jLabel_alertaD = new javax.swing.JLabel();
        jLabel_cursoBuscadD = new javax.swing.JLabel();
        jLabel_nomeBuscadoD = new javax.swing.JLabel();
        jLabel_nomeD = new javax.swing.JLabel();
        jLabel_cursoD = new javax.swing.JLabel();
        jLabel_numChaveD = new javax.swing.JLabel();
        jLabel_ChaveBuscadaD = new javax.swing.JLabel();
        jButton_Devolver = new javax.swing.JButton();
        jLabel_subtitulo = new javax.swing.JLabel();
        jSeparator_topo = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(876, 712));
        setResizable(false);

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Sistema de empréstimo de chaves");

        jPanel_menor1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_menor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_CadastrarChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_CadastrarChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/key.png"))); // NOI18N
        jButton_CadastrarChave.setText("Cadastrar Chave");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bem vindo (a) ");

        jButton_ListaAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_ListaAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ui-list-box-blue.png"))); // NOI18N
        jButton_ListaAluno.setText("Lista Aluno");
        jButton_ListaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListaAlunoActionPerformed(evt);
            }
        });

        jLabel_dataAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_dataAtual.setText("Data atual:");

        jLabel_dataBuscada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_dataBuscada.setText("10/01/2013");

        jLabel_horaBuscada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_horaBuscada.setText("15:37");

        jLabel_horaAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_horaAtual.setText("Hora atual:");

        jLabel_NomeUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NomeUser.setText("Nome do Usuario");

        jButton_EmprestimoDevolucao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_EmprestimoDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/exchange.png"))); // NOI18N
        jButton_EmprestimoDevolucao.setText("Emprestimo e Devolução");
        jButton_EmprestimoDevolucao.setOpaque(false);

        jButton_Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/gnome-logout.png"))); // NOI18N
        jButton_Logout.setText("Sair");

        javax.swing.GroupLayout jPanel_menor1Layout = new javax.swing.GroupLayout(jPanel_menor1);
        jPanel_menor1.setLayout(jPanel_menor1Layout);
        jPanel_menor1Layout.setHorizontalGroup(
            jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menor1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menor1Layout.createSequentialGroup()
                        .addComponent(jLabel_dataAtual)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel_dataBuscada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_menor1Layout.createSequentialGroup()
                        .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_menor1Layout.createSequentialGroup()
                                .addComponent(jLabel_horaAtual)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_horaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_menor1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_NomeUser)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menor1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menor1Layout.createSequentialGroup()
                        .addComponent(jButton_Logout)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menor1Layout.createSequentialGroup()
                        .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_ListaAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_CadastrarChave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_EmprestimoDevolucao, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel_menor1Layout.setVerticalGroup(
            jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menor1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_NomeUser))
                .addGap(77, 77, 77)
                .addComponent(jButton_EmprestimoDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CadastrarChave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ListaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dataAtual)
                    .addComponent(jLabel_dataBuscada))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_horaAtual)
                    .addComponent(jLabel_horaBuscada))
                .addGap(27, 27, 27)
                .addComponent(jButton_Logout)
                .addGap(19, 19, 19))
        );

        jLabel_logoUnipampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/logo unipampa menor.jpg"))); // NOI18N
        jLabel_logoUnipampa.setMaximumSize(new java.awt.Dimension(448, 265));
        jLabel_logoUnipampa.setMinimumSize(new java.awt.Dimension(448, 265));

        jPanel_menor.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_menor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscar.setText("Matrícula:");

        jTF_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_matriculaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_matriculaBuscarActionPerformed(evt);
            }
        });
        jTF_matriculaBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_matriculaBuscarKeyPressed(evt);
            }
        });

        jButton_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/Search.png"))); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nome.setText("Nome:");

        jLabel_curso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_curso.setText("Curso:");

        jLabel_nomeBuscado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeBuscado.setText("Fulano de tal");

        jLabel_cursoBuscad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoBuscad.setText("Engenharia de Telecomunicações");

        jLabel_numChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numChave.setText("Número da chave:");

        jComboBox_listaNumChavesMenores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaNumChavesMenores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        jComboBox_listaNumChavesMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaNumChavesMenoresActionPerformed(evt);
            }
        });

        jButton_realizarEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_realizarEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_realizarEmprestimo.setText("Realizar Empréstimo");
        jButton_realizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_realizarEmprestimoActionPerformed(evt);
            }
        });

        jComboBox_listaNumChavesMaiores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaNumChavesMaiores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61" }));
        jComboBox_listaNumChavesMaiores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaNumChavesMaioresActionPerformed(evt);
            }
        });

        jRadioButton_armarioMaior.setBackground(new java.awt.Color(204, 255, 204));
        jRadioButton_armarioMaior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_armarioMaior.setText("Armario maior:");
        jRadioButton_armarioMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_armarioMaiorActionPerformed(evt);
            }
        });

        jRadioButton_armarioMenor.setBackground(new java.awt.Color(204, 255, 204));
        jRadioButton_armarioMenor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_armarioMenor.setText("Armário menor:");
        jRadioButton_armarioMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_armarioMenorActionPerformed(evt);
            }
        });

        jLabel_alerta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alerta.setText("Empréstimo");

        jLabel_alerta1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alerta1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alerta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alerta1.setText("Aluno não encontrado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Devolução");

        jLabel_matriculaBuscarD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscarD.setText("Matrícula:");

        jTF_matriculaBuscarD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_matriculaBuscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_matriculaBuscarDActionPerformed(evt);
            }
        });

        jButton_buscarD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/Search.png"))); // NOI18N
        jButton_buscarD.setText("Buscar");
        jButton_buscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarDActionPerformed(evt);
            }
        });

        jLabel_alertaD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alertaD.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alertaD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alertaD.setText("Aluno não encontrado");

        jLabel_cursoBuscadD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoBuscadD.setText("Engenharia de Telecomunicações");

        jLabel_nomeBuscadoD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeBuscadoD.setText("Fulano de tal");

        jLabel_nomeD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeD.setText("Nome:");

        jLabel_cursoD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoD.setText("Curso:");

        jLabel_numChaveD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numChaveD.setText("Número da chave:");

        jLabel_ChaveBuscadaD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ChaveBuscadaD.setText("23");

        jButton_Devolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Devolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_Devolver.setText("Realizar Devolução");

        javax.swing.GroupLayout jPanel_menorLayout = new javax.swing.GroupLayout(jPanel_menor);
        jPanel_menor.setLayout(jPanel_menorLayout);
        jPanel_menorLayout.setHorizontalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButton_Devolver)
                .addContainerGap())
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel_cursoBuscadD, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jLabel_matriculaBuscarD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buscarD)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_alertaD, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jLabel_nomeD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nomeBuscadoD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_cursoD))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jLabel_numChaveD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ChaveBuscadaD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_armarioMenor)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_armarioMaior)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_listaNumChavesMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jComboBox_listaNumChavesMaiores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_realizarEmprestimo))))
                            .addComponent(jLabel_numChave))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jLabel_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel_cursoBuscad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addComponent(jLabel_curso)
                                .addContainerGap(47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jLabel_matriculaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_alerta1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addComponent(jSeparator_meio3)
                        .addContainerGap())
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_alerta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_menorLayout.setVerticalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel_alerta)
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar)
                    .addComponent(jLabel_matriculaBuscar)
                    .addComponent(jLabel_alerta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_curso)
                    .addComponent(jLabel_cursoBuscad))
                .addGap(18, 18, 18)
                .addComponent(jLabel_numChave)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_armarioMenor)
                            .addComponent(jComboBox_listaNumChavesMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_listaNumChavesMaiores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_armarioMaior)))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton_realizarEmprestimo)))
                .addGap(43, 43, 43)
                .addComponent(jSeparator_meio3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_matriculaBuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscarD)
                    .addComponent(jLabel_matriculaBuscarD)
                    .addComponent(jLabel_alertaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nomeD)
                    .addComponent(jLabel_nomeBuscadoD, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cursoD)
                    .addComponent(jLabel_cursoBuscadD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numChaveD)
                    .addComponent(jLabel_ChaveBuscadaD, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton_Devolver)
                .addGap(33, 33, 33))
        );

        jLabel_subtitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_subtitulo.setText("Armários da Biblioteca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel_logoUnipampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_menor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_menor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator_topo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_logoUnipampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_titulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator_topo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_menor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_menor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(519, 519, 519))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ListaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ListaAlunoActionPerformed

    private void jButton_buscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_buscarDActionPerformed

    private void jTF_matriculaBuscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_matriculaBuscarDActionPerformed

    private void jRadioButton_armarioMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_armarioMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_armarioMenorActionPerformed

    private void jRadioButton_armarioMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_armarioMaiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_armarioMaiorActionPerformed

    private void jComboBox_listaNumChavesMaioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaNumChavesMaioresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaNumChavesMaioresActionPerformed

    private void jButton_realizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_realizarEmprestimoActionPerformed
          Senha senha =new Senha();
          senha.setVisible(true);
    }//GEN-LAST:event_jButton_realizarEmprestimoActionPerformed

    private void jComboBox_listaNumChavesMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaNumChavesMenoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaNumChavesMenoresActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        //this.jButton_buscar.setBack
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTF_matriculaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTF_matriculaBuscarActionPerformed

    private void jTF_matriculaBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            //Add o metodo
        }
    }//GEN-LAST:event_jTF_matriculaBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoDevolucao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastrarChave;
    private javax.swing.JButton jButton_Devolver;
    private javax.swing.JButton jButton_EmprestimoDevolucao;
    private javax.swing.JButton jButton_ListaAluno;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_buscarD;
    private javax.swing.JButton jButton_realizarEmprestimo;
    private javax.swing.JComboBox jComboBox_listaNumChavesMaiores;
    private javax.swing.JComboBox jComboBox_listaNumChavesMenores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ChaveBuscadaD;
    private javax.swing.JLabel jLabel_NomeUser;
    private javax.swing.JLabel jLabel_alerta;
    private javax.swing.JLabel jLabel_alerta1;
    private javax.swing.JLabel jLabel_alertaD;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_cursoBuscad;
    private javax.swing.JLabel jLabel_cursoBuscadD;
    private javax.swing.JLabel jLabel_cursoD;
    private javax.swing.JLabel jLabel_dataAtual;
    private javax.swing.JLabel jLabel_dataBuscada;
    private javax.swing.JLabel jLabel_horaAtual;
    private javax.swing.JLabel jLabel_horaBuscada;
    private javax.swing.JLabel jLabel_logoUnipampa;
    private javax.swing.JLabel jLabel_matriculaBuscar;
    private javax.swing.JLabel jLabel_matriculaBuscarD;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_nomeBuscado;
    private javax.swing.JLabel jLabel_nomeBuscadoD;
    private javax.swing.JLabel jLabel_nomeD;
    private javax.swing.JLabel jLabel_numChave;
    private javax.swing.JLabel jLabel_numChaveD;
    private javax.swing.JLabel jLabel_subtitulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel_menor;
    private javax.swing.JPanel jPanel_menor1;
    private javax.swing.JRadioButton jRadioButton_armarioMaior;
    private javax.swing.JRadioButton jRadioButton_armarioMenor;
    private javax.swing.JSeparator jSeparator_meio3;
    private javax.swing.JSeparator jSeparator_topo;
    private javax.swing.JTextField jTF_matriculaBuscar;
    private javax.swing.JTextField jTF_matriculaBuscarD;
    // End of variables declaration//GEN-END:variables
}
