/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Kooler
 */
public class Emprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Emprestimo
     */
    public Emprestimo() {
        initComponents();
        
        this.setResizable(false);
        //this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloJanela = new javax.swing.JLabel();
        jSeparator_topo = new javax.swing.JSeparator();
        jPanel_menor = new javax.swing.JPanel();
        jLabel_matriculaBuscar = new javax.swing.JLabel();
        jTF_matriculaBuscar = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jSeparator_meio = new javax.swing.JSeparator();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_matricula = new javax.swing.JLabel();
        jLabel_curso = new javax.swing.JLabel();
        jLabel_dataAtual = new javax.swing.JLabel();
        jLabel_horaAtual = new javax.swing.JLabel();
        jLabel_nomeBuscado = new javax.swing.JLabel();
        jLabel_matriculaBuscada = new javax.swing.JLabel();
        jLabel_cursoBuscad = new javax.swing.JLabel();
        jLabel_numChave = new javax.swing.JLabel();
        jComboBox_listaNumChaves = new javax.swing.JComboBox();
        jButton_realizarEmprestimo = new javax.swing.JButton();
        jLabel_statusAluno = new javax.swing.JLabel();
        jLabel_dataBuscada = new javax.swing.JLabel();
        jLabel_horaBuscada = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloJanela.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_tituloJanela.setText("Sistema de empréstimo de chaves");

        jPanel_menor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscar.setText("Matrícula:");

        jTF_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/Search.png"))); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nome.setText("Nome:");

        jLabel_matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matricula.setText("Matrícula:");

        jLabel_curso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_curso.setText("Curso:");

        jLabel_dataAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_dataAtual.setText("Data atual:");

        jLabel_horaAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_horaAtual.setText("Hora atual:");

        jLabel_nomeBuscado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeBuscado.setText("Fulano de tal");

        jLabel_matriculaBuscada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscada.setText("123456");

        jLabel_cursoBuscad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoBuscad.setText("Ciência da Computação");

        jLabel_numChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numChave.setText("Número da chave:");

        jComboBox_listaNumChaves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaNumChaves.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jButton_realizarEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_realizarEmprestimo.setText("Realizar Empréstimo");

        jLabel_statusAluno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_statusAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_statusAluno.setText("Status aluno");

        jLabel_dataBuscada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_dataBuscada.setText("10/01/2013");

        jLabel_horaBuscada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_horaBuscada.setText("15:37");

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel.setText("Aluno não encontrado");

        javax.swing.GroupLayout jPanel_menorLayout = new javax.swing.GroupLayout(jPanel_menor);
        jPanel_menor.setLayout(jPanel_menorLayout);
        jPanel_menorLayout.setHorizontalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_matriculaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addComponent(jLabel_numChave)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_statusAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jComboBox_listaNumChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_realizarEmprestimo)
                                        .addGap(199, 199, 199))))
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jLabel_horaAtual)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_horaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_nome)
                                            .addComponent(jLabel_curso)
                                            .addComponent(jLabel_dataAtual))
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel_dataBuscada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_cursoBuscad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                                .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_matricula)
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel_matriculaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(173, 173, 173))))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator_meio, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_menorLayout.setVerticalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar)
                    .addComponent(jLabel_matriculaBuscar)
                    .addComponent(jLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator_meio, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_nome)
                        .addComponent(jLabel_matriculaBuscada)
                        .addComponent(jLabel_matricula)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_curso)
                    .addComponent(jLabel_cursoBuscad))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dataAtual)
                    .addComponent(jLabel_dataBuscada))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_horaAtual)
                    .addComponent(jLabel_horaBuscada))
                .addGap(35, 35, 35)
                .addComponent(jLabel_statusAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_realizarEmprestimo)
                    .addComponent(jLabel_numChave)
                    .addComponent(jComboBox_listaNumChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/logo unipampa menor.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(448, 265));
        jLabel1.setMinimumSize(new java.awt.Dimension(448, 265));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel_tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator_topo, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_menor, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel_tituloJanela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator_topo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        //this.jButton_buscar.setBack
    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestimo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_realizarEmprestimo;
    private javax.swing.JComboBox jComboBox_listaNumChaves;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_cursoBuscad;
    private javax.swing.JLabel jLabel_dataAtual;
    private javax.swing.JLabel jLabel_dataBuscada;
    private javax.swing.JLabel jLabel_horaAtual;
    private javax.swing.JLabel jLabel_horaBuscada;
    private javax.swing.JLabel jLabel_matricula;
    private javax.swing.JLabel jLabel_matriculaBuscada;
    private javax.swing.JLabel jLabel_matriculaBuscar;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_nomeBuscado;
    private javax.swing.JLabel jLabel_numChave;
    private javax.swing.JLabel jLabel_statusAluno;
    private javax.swing.JLabel jLabel_tituloJanela;
    private javax.swing.JPanel jPanel_menor;
    private javax.swing.JSeparator jSeparator_meio;
    private javax.swing.JSeparator jSeparator_topo;
    private javax.swing.JTextField jTF_matriculaBuscar;
    // End of variables declaration//GEN-END:variables
}
