/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

/**
 *
 * @author Kooler
 */
public class Emprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Emprestimo
     */
    public Emprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloJanela = new javax.swing.JLabel();
        jSeparator_topo = new javax.swing.JSeparator();
        jPanel_menor = new javax.swing.JPanel();
        jLabel_matriculaBuscar = new javax.swing.JLabel();
        jTF_matriculaBuscar = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_nome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_matricula = new javax.swing.JLabel();
        jLabel_curso = new javax.swing.JLabel();
        jLabel_dataAtual = new javax.swing.JLabel();
        jLabel_horaAtual = new javax.swing.JLabel();
        jLabel_nomeBuscado = new javax.swing.JLabel();
        jLabel_matriculaBuscada = new javax.swing.JLabel();
        jLabel_cursoBuscad = new javax.swing.JLabel();
        jLabel_mensagemStatus = new javax.swing.JLabel();
        jLabel_numChave = new javax.swing.JLabel();
        jComboBox_listaNumChaves = new javax.swing.JComboBox();
        jButton_realizarEmprestimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloJanela.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_tituloJanela.setText("Sistema de empréstimo de chaves");

        jPanel_menor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_matriculaBuscar.setText("Matrícula:");

        jButton_buscar.setText("Buscar");

        jLabel_nome.setText("Nome:");

        jLabel_matricula.setText("Matrícula:");

        jLabel_curso.setText("Curso:");

        jLabel_dataAtual.setText("Data atual:");

        jLabel_horaAtual.setText("Hora atual:");

        jLabel_nomeBuscado.setText("Fulano de tal");

        jLabel_matriculaBuscada.setText("123456");

        jLabel_cursoBuscad.setText("Ciência da Computação");

        jLabel_mensagemStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_mensagemStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_mensagemStatus.setText("Mensagem de status");

        jLabel_numChave.setText("Número da chave:");

        jComboBox_listaNumChaves.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jButton_realizarEmprestimo.setText("Realizar Empréstimo");

        javax.swing.GroupLayout jPanel_menorLayout = new javax.swing.GroupLayout(jPanel_menor);
        jPanel_menor.setLayout(jPanel_menorLayout);
        jPanel_menorLayout.setHorizontalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_matriculaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_buscar))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_horaAtual)
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jLabel_nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel_curso))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_cursoBuscad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                                        .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel_matricula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_matriculaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel_dataAtual)
                            .addGroup(jPanel_menorLayout.createSequentialGroup()
                                .addComponent(jLabel_numChave)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_listaNumChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel_mensagemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_menorLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton_realizarEmprestimo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_menorLayout.setVerticalGroup(
            jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar)
                    .addComponent(jLabel_matriculaBuscar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nomeBuscado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_nome)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel_matriculaBuscada)
                        .addComponent(jLabel_matricula)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_curso)
                    .addComponent(jLabel_cursoBuscad))
                .addGap(18, 18, 18)
                .addComponent(jLabel_dataAtual)
                .addGap(18, 18, 18)
                .addComponent(jLabel_horaAtual)
                .addGap(18, 18, 18)
                .addComponent(jLabel_mensagemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numChave)
                    .addComponent(jComboBox_listaNumChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_realizarEmprestimo)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel_tituloJanela))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator_topo, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_menor, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_tituloJanela)
                .addGap(18, 18, 18)
                .addComponent(jSeparator_topo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestimo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_realizarEmprestimo;
    private javax.swing.JComboBox jComboBox_listaNumChaves;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_curso;
    private javax.swing.JLabel jLabel_cursoBuscad;
    private javax.swing.JLabel jLabel_dataAtual;
    private javax.swing.JLabel jLabel_horaAtual;
    private javax.swing.JLabel jLabel_matricula;
    private javax.swing.JLabel jLabel_matriculaBuscada;
    private javax.swing.JLabel jLabel_matriculaBuscar;
    private javax.swing.JLabel jLabel_mensagemStatus;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_nomeBuscado;
    private javax.swing.JLabel jLabel_numChave;
    private javax.swing.JLabel jLabel_tituloJanela;
    private javax.swing.JPanel jPanel_menor;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator_topo;
    private javax.swing.JTextField jTF_matriculaBuscar;
    // End of variables declaration//GEN-END:variables
}
