/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

import com.ideiah.controller.AlunoController;
import com.ideiah.model.entity.Aluno;
import java.util.List;

/**
 *
 * @author Kooler
 */
public class PainelEmprestimoDevolucao extends javax.swing.JPanel {

    /**
     * Creates new form PainelEmprestimoDevoolucao
     */
    private String matricula;
    private AlunoController alunoController;
    private Aluno aluno;
     
    public PainelEmprestimoDevolucao() {
        initComponents();
        this.jTF_matriculaBuscar.grabFocus();
    }

 

    
    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    
    private Aluno buscarAluno(){
       alunoController = new AlunoController();
       aluno  = alunoController.pesquisarPorMatricula(this.getMatricula());
       return aluno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_matriculaBuscar = new javax.swing.JLabel();
        jTF_matriculaBuscar = new javax.swing.JTextField();
        jButton_buscar2 = new javax.swing.JButton();
        jLabel_nome2 = new javax.swing.JLabel();
        jLabel_curso2 = new javax.swing.JLabel();
        jLabel_nomeBuscado2 = new javax.swing.JLabel();
        jLabel_cursoBuscad2 = new javax.swing.JLabel();
        jLabel_numChave2 = new javax.swing.JLabel();
        jComboBox_listaNumChavesMenores2 = new javax.swing.JComboBox();
        jButton_realizarEmprestimo2 = new javax.swing.JButton();
        jComboBox_listaNumChavesMaiores2 = new javax.swing.JComboBox();
        jRadioButton_armarioMaior2 = new javax.swing.JRadioButton();
        jRadioButton_armarioMenor2 = new javax.swing.JRadioButton();
        jLabel_alerta4 = new javax.swing.JLabel();
        jSeparator_meio5 = new javax.swing.JSeparator();
        jLabel_alerta5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_matriculaBuscarD2 = new javax.swing.JLabel();
        jTF_matriculaBuscarD2 = new javax.swing.JTextField();
        jButton_buscarD2 = new javax.swing.JButton();
        jLabel_alertaD2 = new javax.swing.JLabel();
        jLabel_cursoBuscadD2 = new javax.swing.JLabel();
        jLabel_nomeBuscadoD2 = new javax.swing.JLabel();
        jLabel_nomeD2 = new javax.swing.JLabel();
        jLabel_cursoD2 = new javax.swing.JLabel();
        jLabel_numChaveD2 = new javax.swing.JLabel();
        jLabel_ChaveBuscadaD2 = new javax.swing.JLabel();
        jButton_Devolver2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(609, 527));

        jLabel_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscar.setText("Matrícula:");

        jTF_matriculaBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_matriculaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_matriculaBuscarActionPerformed(evt);
            }
        });
        jTF_matriculaBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_matriculaBuscarKeyPressed(evt);
            }
        });

        jButton_buscar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/Search.png"))); // NOI18N
        jButton_buscar2.setText("Buscar");
        jButton_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar2ActionPerformed(evt);
            }
        });

        jLabel_nome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nome2.setText("Nome:");

        jLabel_curso2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_curso2.setText("Curso:");

        jLabel_nomeBuscado2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeBuscado2.setText("Fulano de tal");

        jLabel_cursoBuscad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoBuscad2.setText("Engenharia de Telecomunicações");

        jLabel_numChave2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numChave2.setText("Número da chave:");

        jComboBox_listaNumChavesMenores2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaNumChavesMenores2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        jComboBox_listaNumChavesMenores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaNumChavesMenores2ActionPerformed(evt);
            }
        });

        jButton_realizarEmprestimo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_realizarEmprestimo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_realizarEmprestimo2.setText("Realizar Empréstimo");
        jButton_realizarEmprestimo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_realizarEmprestimo2ActionPerformed(evt);
            }
        });

        jComboBox_listaNumChavesMaiores2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaNumChavesMaiores2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61" }));
        jComboBox_listaNumChavesMaiores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaNumChavesMaiores2ActionPerformed(evt);
            }
        });

        jRadioButton_armarioMaior2.setBackground(new java.awt.Color(204, 255, 204));
        jRadioButton_armarioMaior2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_armarioMaior2.setText("Armario maior:");
        jRadioButton_armarioMaior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_armarioMaior2ActionPerformed(evt);
            }
        });

        jRadioButton_armarioMenor2.setBackground(new java.awt.Color(204, 255, 204));
        jRadioButton_armarioMenor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_armarioMenor2.setText("Armário menor:");
        jRadioButton_armarioMenor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_armarioMenor2ActionPerformed(evt);
            }
        });

        jLabel_alerta4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_alerta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alerta4.setText("Empréstimo");

        jLabel_alerta5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alerta5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alerta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alerta5.setText("Aluno não encontrado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Devolução");

        jLabel_matriculaBuscarD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_matriculaBuscarD2.setText("Matrícula:");

        jTF_matriculaBuscarD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_matriculaBuscarD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_matriculaBuscarD2ActionPerformed(evt);
            }
        });

        jButton_buscarD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscarD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/Search.png"))); // NOI18N
        jButton_buscarD2.setText("Buscar");
        jButton_buscarD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarD2ActionPerformed(evt);
            }
        });

        jLabel_alertaD2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_alertaD2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_alertaD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alertaD2.setText("Aluno não encontrado");

        jLabel_cursoBuscadD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoBuscadD2.setText("Engenharia de Telecomunicações");

        jLabel_nomeBuscadoD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeBuscadoD2.setText("Fulano de tal");

        jLabel_nomeD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_nomeD2.setText("Nome:");

        jLabel_cursoD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cursoD2.setText("Curso:");

        jLabel_numChaveD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numChaveD2.setText("Número da chave:");

        jLabel_ChaveBuscadaD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ChaveBuscadaD2.setText("23");

        jButton_Devolver2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Devolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_Devolver2.setText("Realizar Devolução");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButton_Devolver2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel_cursoBuscadD2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_matriculaBuscarD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscarD2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buscarD2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_alertaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_nomeD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nomeBuscadoD2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel_cursoD2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_numChaveD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ChaveBuscadaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_armarioMenor2)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton_armarioMaior2)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_listaNumChavesMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_listaNumChavesMaiores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_realizarEmprestimo2))))
                            .addComponent(jLabel_numChave2))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_nome2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_nomeBuscado2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel_cursoBuscad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_curso2)
                                .addContainerGap(47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_matriculaBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buscar2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_alerta5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator_meio5)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_alerta4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel_alerta4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_buscar2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_matriculaBuscar)
                        .addComponent(jLabel_alerta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome2)
                    .addComponent(jLabel_nomeBuscado2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_curso2)
                    .addComponent(jLabel_cursoBuscad2))
                .addGap(18, 18, 18)
                .addComponent(jLabel_numChave2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_armarioMenor2)
                            .addComponent(jComboBox_listaNumChavesMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_listaNumChavesMaiores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_armarioMaior2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton_realizarEmprestimo2)))
                .addGap(43, 43, 43)
                .addComponent(jSeparator_meio5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_buscarD2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_matriculaBuscarD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_matriculaBuscarD2)
                        .addComponent(jLabel_alertaD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nomeD2)
                    .addComponent(jLabel_nomeBuscadoD2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cursoD2)
                    .addComponent(jLabel_cursoBuscadD2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numChaveD2)
                    .addComponent(jLabel_ChaveBuscadaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton_Devolver2)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_matriculaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_matriculaBuscarActionPerformed

    private void jTF_matriculaBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
           this.setMatricula(this.jTF_matriculaBuscar.getText());
           aluno = this.buscarAluno();
            
        }

    }//GEN-LAST:event_jTF_matriculaBuscarKeyPressed

    private void jButton_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar2ActionPerformed
        // TODO add your handling code here:
        //this.jButton_buscar.setBack
    }//GEN-LAST:event_jButton_buscar2ActionPerformed

    private void jComboBox_listaNumChavesMenores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaNumChavesMenores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaNumChavesMenores2ActionPerformed

    private void jButton_realizarEmprestimo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_realizarEmprestimo2ActionPerformed
        Senha senha =new Senha();
        senha.setVisible(false);
    }//GEN-LAST:event_jButton_realizarEmprestimo2ActionPerformed

    private void jComboBox_listaNumChavesMaiores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaNumChavesMaiores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaNumChavesMaiores2ActionPerformed

    private void jRadioButton_armarioMaior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_armarioMaior2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_armarioMaior2ActionPerformed

    private void jRadioButton_armarioMenor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_armarioMenor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_armarioMenor2ActionPerformed

    private void jTF_matriculaBuscarD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_matriculaBuscarD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_matriculaBuscarD2ActionPerformed

    private void jButton_buscarD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_buscarD2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Devolver2;
    private javax.swing.JButton jButton_buscar2;
    private javax.swing.JButton jButton_buscarD2;
    private javax.swing.JButton jButton_realizarEmprestimo2;
    private javax.swing.JComboBox jComboBox_listaNumChavesMaiores2;
    private javax.swing.JComboBox jComboBox_listaNumChavesMenores2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_ChaveBuscadaD2;
    private javax.swing.JLabel jLabel_alerta4;
    private javax.swing.JLabel jLabel_alerta5;
    private javax.swing.JLabel jLabel_alertaD2;
    private javax.swing.JLabel jLabel_curso2;
    private javax.swing.JLabel jLabel_cursoBuscad2;
    private javax.swing.JLabel jLabel_cursoBuscadD2;
    private javax.swing.JLabel jLabel_cursoD2;
    private javax.swing.JLabel jLabel_matriculaBuscar;
    private javax.swing.JLabel jLabel_matriculaBuscarD2;
    private javax.swing.JLabel jLabel_nome2;
    private javax.swing.JLabel jLabel_nomeBuscado2;
    private javax.swing.JLabel jLabel_nomeBuscadoD2;
    private javax.swing.JLabel jLabel_nomeD2;
    private javax.swing.JLabel jLabel_numChave2;
    private javax.swing.JLabel jLabel_numChaveD2;
    private javax.swing.JRadioButton jRadioButton_armarioMaior2;
    private javax.swing.JRadioButton jRadioButton_armarioMenor2;
    private javax.swing.JSeparator jSeparator_meio5;
    private javax.swing.JTextField jTF_matriculaBuscar;
    private javax.swing.JTextField jTF_matriculaBuscarD2;
    // End of variables declaration//GEN-END:variables
}
