/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ideiah.views.emprestimo;

import com.ideiah.controller.AlunoController;
import com.ideiah.controller.ChaveController;
import com.ideiah.model.entity.Aluno;
import com.ideiah.model.entity.Chave;
import java.util.List;

/**
 *
 * @author Kooler
 */
public class PainelCadastroChave extends javax.swing.JPanel {

    /**
     * Creates new form PainelEmprestimoDevoolucao
     */
    private String matricula;
    private AlunoController alunoController;
    private Aluno aluno;
     
    public PainelCadastroChave() {
        initComponents();
//        this.jTF_matriculaBuscarE.grabFocus();
    }

 

    
    public String getMatricula() {
        return matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    
    private Aluno buscarAluno(){
       alunoController = new AlunoController();
       aluno  = alunoController.pesquisarPorMatricula(this.getMatricula());
       return aluno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cadNumero = new javax.swing.JLabel();
        jTF_cadNumChave = new javax.swing.JTextField();
        jButton_cadastrar = new javax.swing.JButton();
        jLabel_cadTamanhoChave = new javax.swing.JLabel();
        jComboBox_listaTamChaves = new javax.swing.JComboBox();
        jLabel_tituloCadastro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(609, 527));

        jLabel_cadNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadNumero.setText("Número da chave:");

        jTF_cadNumChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_cadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ideiah/views/imagens/ok.png"))); // NOI18N
        jButton_cadastrar.setText("Cadastrar");
        jButton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarActionPerformed(evt);
            }
        });

        jLabel_cadTamanhoChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cadTamanhoChave.setText("Número da chave:");

        jComboBox_listaTamChaves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_listaTamChaves.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Menor", "Maior" }));
        jComboBox_listaTamChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_listaTamChavesActionPerformed(evt);
            }
        });

        jLabel_tituloCadastro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_tituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tituloCadastro.setText("Cadastro de novo número de chave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_tituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cadNumero)
                            .addComponent(jLabel_cadTamanhoChave))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTF_cadNumChave)
                                .addComponent(jComboBox_listaTamChaves, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_tituloCadastro)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_cadNumChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cadNumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cadTamanhoChave)
                    .addComponent(jComboBox_listaTamChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jButton_cadastrar)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarActionPerformed
        // TODO add your handling code here:
        //this.jButton_buscar.setBack
        Chave chave = new Chave();
        chave.setNumero(Integer.decode(this.jTF_cadNumChave.getText()));
        String tipo = (String)this.jComboBox_listaTamChaves.getItemAt(
                this.jComboBox_listaTamChaves.getSelectedIndex());
        tipo = tipo.toLowerCase();
        chave.setTipo(tipo);
        chave.setDisponivel(true);
        ChaveController cc = new ChaveController();
        cc.setChave(chave);
        cc.salvar();
    }//GEN-LAST:event_jButton_cadastrarActionPerformed

    private void jComboBox_listaTamChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_listaTamChavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_listaTamChavesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar;
    private javax.swing.JComboBox jComboBox_listaTamChaves;
    private javax.swing.JLabel jLabel_cadNumero;
    private javax.swing.JLabel jLabel_cadTamanhoChave;
    private javax.swing.JLabel jLabel_tituloCadastro;
    private javax.swing.JTextField jTF_cadNumChave;
    // End of variables declaration//GEN-END:variables
}
